export class SHARED_CONSTANTS {
  public static MAIN_MENU_LIST = ["DASHBOARD", "QA", "ADMIN"];

  public static EVU_USER_ROLES = {
    SUPER_USER: "ENTERVU_ROLE_SUPER_USER",
    HR_ADMIN: "ENTERVU_ROLE_HR_ADMIN",
    HR_USER: "ENTERVU_ROLE_HR_USER",
    CANDIDATE: "ENTERVU_ROLE_CANDIDATE",
  };

  public static EVU_LOCAL_STORAGES = {
    LS_EVU_USER_ROLE: "LS_EVU_USER_ROLE",
    LS_EVU_SESSION_TOKEN: "LS_EVU_SESSION_TOKEN",
    LS_EVU_USER_DETAILS: "LS_EVU_USER_DETAILS",
  };
}
