import { ROUTE_URL_PATH_CONSTANTS } from "../constants/route-url-path.constants";

export class SHARED_CONSTANTS {
  public static EVU_USER_ROLES = {
    SUPER_USER: "ENTERVU_ROLE_SUPER_USER",
    HR_ADMIN: "ENTERVU_ROLE_HR_ADMIN",
    HR_USER: "ENTERVU_ROLE_HR_USER",
    CANDIDATE: "ENTERVU_ROLE_CANDIDATE",
  };

  public static EVU_LOCAL_STORAGES = {
    LS_EVU_USER_ROLE: "LS_EVU_USER_ROLE",
    LS_EVU_SESSION_TOKEN: "LS_EVU_SESSION_TOKEN",
    LS_EVU_USER_DETAILS: "LS_EVU_USER_DETAILS",
  };

  public static MAIN_MENU = {
    ORGANIZATION_MENU_LIST: [
      {
        DISPLAY_TEXT: "EVENTS",
        NAVIGATE_TO:
          ROUTE_URL_PATH_CONSTANTS.ROUTE_URL_PATH.ORGANIZATION_DASHBOARD,
      },
      {
        DISPLAY_TEXT: "TEAM",
        NAVIGATE_TO: ROUTE_URL_PATH_CONSTANTS.ROUTE_URL_PATH.MANAGE_TEAM,
      },
    ],
    INDIVIDUAL_MENU_LIST: [
      {
        DISPLAY_TEXT: "DASHBOARD",
        NAVIGATE_TO:
          ROUTE_URL_PATH_CONSTANTS.ROUTE_URL_PATH.INDIVIDUAL_DASHBOARD,
      },
      {
        DISPLAY_TEXT: "QA",
        NAVIGATE_TO: ROUTE_URL_PATH_CONSTANTS.ROUTE_URL_PATH.QA_DASHBOARD,
      },
    ],
    SUPER_USER_MENU_LIST: [
      {
        DISPLAY_TEXT: "EVENTS",
        NAVIGATE_TO:
          ROUTE_URL_PATH_CONSTANTS.ROUTE_URL_PATH.ORGANIZATION_DASHBOARD,
      },
      {
        DISPLAY_TEXT: "TEAM",
        NAVIGATE_TO: ROUTE_URL_PATH_CONSTANTS.ROUTE_URL_PATH.MANAGE_TEAM,
      },
      {
        DISPLAY_TEXT: "DASHBOARD",
        NAVIGATE_TO:
          ROUTE_URL_PATH_CONSTANTS.ROUTE_URL_PATH.INDIVIDUAL_DASHBOARD,
      },
      {
        DISPLAY_TEXT: "QA",
        NAVIGATE_TO: ROUTE_URL_PATH_CONSTANTS.ROUTE_URL_PATH.QA_DASHBOARD,
      },
      {
        DISPLAY_TEXT: "ADMIN",
        NAVIGATE_TO: ROUTE_URL_PATH_CONSTANTS.ROUTE_URL_PATH.ADMIN,
      },
    ],
  };
}
